[versions]
paper-api = "1.21.11-R0.1-SNAPSHOT"
minecraft = "1.21.11"
turbo-messages = "1.1.0"
run-paper = "3.1.0"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
turbo-messages = { module = "org.turbojax:messages", version.ref = "turbo-messages" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
